### ISSUE TITLE
Doubts about the logo

### ISSUE THREAD

**Issue by haggen88** [linuxmint/brand-logo#10]
In the case of using the "Ring" logo with a white border on a light background, the circumference is lost and the proportions change.   Is it possible to consider a "Ring" logo with a border or a shadow ?.   
Like these:  [Logo-Ring-Filled+shadow](https://github.com/SebastJava/linuxmint-logo/blob/master/special-requests/Logo-Ring-Filled%2Bshadow-%2386BE43.svg)  -  [Logo-Ring-Filled+outline](https://github.com/SebastJava/linuxmint-logo/blob/master/special-requests/Logo-Ring-Filled%2Boutline-%2386BE43.svg) by @SebastJava

Or will it simply be suggested to use the "Badge" logo? .
Best regards

**Comment by clefebvre** [comment]
Good point, I think we indeed should add shadow and bordered versions.

**Comment by SebastJava** [comment]
ring-back.svg, ring-name-back.svg and ring-name-back-grn.svg half-closes this.

I didn't do the shadow version because such a version is more like material design, while everything else here is more like flat design. Of course, i could always change my mind later...
